# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de05b9cfea2b86812580e4b556de089ec0efa34fcae9c20dea9f2a2afe58b5c69d6925f386de9ef9e7590e860bd20f2cc413d18ca97ea6bcef5cce80ba42d529

test:
  secret_key_base: 89d3817ef645a701f99713ce789d7ee1ba4149e740ded53907992496d3e5fa5dcbe24be8cc8f84cb40e2ab1ab1851f6fbc452b330188fb5c3809dcf839578353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
